drop table if exists tb_member cascade;
create table tb_member (
    seq bigint generated by default as identity,
    login_id varchar(50) not null unique,
    password varchar(100) not null,
    name varchar(50) not null,
    last_active_at timestamp(6),
    primary key (seq)
);
CREATE INDEX idx_member_last_active_at ON tb_member(last_active_at);