INSERT INTO tb_member (login_id, password, name, last_active_at)
VALUES ('string', '$2a$10$YYCgKcbHhcryQI8CMYIBkeksrwI66y9Oa3KqHzzKQgMhQAG5yDSJC', '조조', DATEADD(MINUTE, -1, now()));
INSERT INTO tb_member (login_id, password, name, last_active_at)
VALUES ('str', '$2a$10$YYCgKcbHhcryQI8CMYIBkeksrwI66y9Oa3KqHzzKQgMhQAG5yDSJC', '유비', DATEADD(MINUTE, -2, now()));
INSERT INTO tb_member (login_id, password, name, last_active_at)
VALUES ('hihi', '$2a$10$YYCgKcbHhcryQI8CMYIBkeksrwI66y9Oa3KqHzzKQgMhQAG5yDSJC', '손권', DATEADD(MINUTE, -3, now()));
INSERT INTO tb_member (login_id, password, name, last_active_at)
VALUES ('abc', '$2a$10$YYCgKcbHhcryQI8CMYIBkeksrwI66y9Oa3KqHzzKQgMhQAG5yDSJC', '제갈량', DATEADD(MINUTE, -4, now()));
INSERT INTO tb_member (login_id, password, name, last_active_at)
VALUES ('qwer', '$2a$10$YYCgKcbHhcryQI8CMYIBkeksrwI66y9Oa3KqHzzKQgMhQAG5yDSJC', '항우', DATEADD(MINUTE, -5, now()));